In [1]:
import sys
import pandas as pd
import numpy as np

from datetime import datetime
from datetime import date
from datetime import timedelta

In [2]:
pd.set_option('display.float_format', lambda x: '%.2f' % x)
pd.set_option('display.max_rows',100)

In [3]:
%matplotlib inline
import matplotlib as mpl
import matplotlib.pyplot as plt

plt.style.use('ggplot')
plt.rcParams['figure.figsize'] = (18.0,8.0)

In [4]:
df0 = pd.read_csv('df_invest_financial_overdue.csv',encoding='utf8')

In [5]:
df0.head()

FuiFinancialId  FuiFinancialInvestId       FuiInvestUid  \
0  82051058471567364     82159496732655619  50514362542866432   
1  82051058471567364     82159496732655619  50514362542866432   
2  82051058471567364     82159496732655619  50514362542866432   
3  82051058471567364     82159496732655619  50514362542866432   
4  82051058471567364     82159496732655619  50514362542866432   

   FuiFinUserGroup  FuiFinPerids  FuiFinDuTime  FuiFinNextRepayTime  \
0                0             1    1509119999           1509119999   
1                0             1    1509119999           1509119999   
2                0             1    1509119999           1509119999   
3                0             1    1509119999           1509119999   
4                0             1    1509119999           1509119999   

   FstrFinRepayPlan        FuiInvestId  FuiNextRepayTime        ...          \
0                 0  82159499952832517        1495641600        ...           
1                 0  82159505322590209        1495641600        ...           
2                 0  82159509617033220        1495641600        ...           
3                 0  82159527870644230        1495641600        ...           
4                 0  82159533239615489        1495641600        ...           

   buy_back_20170503  buy_back_20170703  buy_back_20170504  buy_back_20180118  \
0                nan                nan                nan                nan   
1                nan                nan                nan                nan   
2                nan                nan                nan                nan   
3                nan                nan                nan                nan   
4                nan                nan                nan                nan   

   buy_back_20180119  continue_invest_20170726  continue_invest_20170731  \
0                nan                       nan                       nan   
1                nan                       nan                       nan   
2                nan                       nan                       nan   
3                nan                       nan                       nan   
4                nan                       nan                       nan   

   continue_invest_20171024  buy_back_20171102  buy_back_20171204  
0                       nan                nan                nan  
1                       nan                nan                nan  
2                       nan                nan                nan  
3                       nan                nan                nan  
4                       nan                nan                nan  

[5 rows x 151 columns]

In [11]:
df0.columns[:26]

Index(['FuiFinancialId', 'FuiFinancialInvestId', 'FuiInvestUid',
       'FuiFinUserGroup', 'FuiFinPerids', 'FuiFinDuTime',
       'FuiFinNextRepayTime', 'FstrFinRepayPlan', 'FuiInvestId',
       'FuiNextRepayTime', 'FuiNextRepayPrincipal', 'FuiNextRepayInterest',
       'FuiToRepayPrincipal', 'FuiRepayDate', 'FuiPeriods', 'FuiCurrentPeriod',
       'FuiType', 'FuiRepayOverdueType', 'continue_invest_20170506',
       'buy_back_20170506', 'continue_invest_20170507', 'buy_back_20170507',
       'continue_invest_20170508', 'buy_back_20170508',
       'continue_invest_20170509', 'buy_back_20170509'],
      dtype='object')

In [12]:
df1 = df0.iloc[:,:26]

In [13]:
df1.shape

(614107, 26)

In [15]:
df1.head()

FuiFinancialId  FuiFinancialInvestId       FuiInvestUid  \
0  82051058471567364     82159496732655619  50514362542866432   
1  82051058471567364     82159496732655619  50514362542866432   
2  82051058471567364     82159496732655619  50514362542866432   
3  82051058471567364     82159496732655619  50514362542866432   
4  82051058471567364     82159496732655619  50514362542866432   

   FuiFinUserGroup  FuiFinPerids  FuiFinDuTime  FuiFinNextRepayTime  \
0                0             1    1509119999           1509119999   
1                0             1    1509119999           1509119999   
2                0             1    1509119999           1509119999   
3                0             1    1509119999           1509119999   
4                0             1    1509119999           1509119999   

   FstrFinRepayPlan        FuiInvestId  FuiNextRepayTime        ...          \
0                 0  82159499952832517        1495641600        ...           
1                 0  82159505322590209        1495641600        ...           
2                 0  82159509617033220        1495641600        ...           
3                 0  82159527870644230        1495641600        ...           
4                 0  82159533239615489        1495641600        ...           

   FuiType  FuiRepayOverdueType  continue_invest_20170506  buy_back_20170506  \
0       26                    0                         0                  0   
1       26                    0                         0                  0   
2       26                    0                         0                  0   
3       26                    0                         0                  0   
4       26                    0                         0                  0   

   continue_invest_20170507  buy_back_20170507  continue_invest_20170508  \
0                         0                  0                         0   
1                         0                  0                         0   
2                         0                  0                         0   
3                         0                  0                         0   
4                         0                  0                         0   

   buy_back_20170508  continue_invest_20170509  buy_back_20170509  
0                  0                         0                  0  
1                  0                         0                  0  
2                  0                         0                  0  
3                  0                         0                  0  
4                  0                         0                  0  

[5 rows x 26 columns]

In [16]:
df1.buy_back_20170509.sum()

22219878848

In [18]:
df2 = df1[df1.buy_back_20170509 > 0]

In [19]:
df2.head()

FuiFinancialId  FuiFinancialInvestId       FuiInvestUid  \
35  82631280635969544     83008387354247174  60737688764956674   
36  82631280635969544     83008387354247174  60737688764956674   
37  82631280635969544     83008387354247174  60737688764956674   
38  82631280635969544     83008387354247174  60737688764956674   
39  82631280635969544     83008387354247174  60737688764956674   

    FuiFinUserGroup  FuiFinPerids  FuiFinDuTime  FuiFinNextRepayTime  \
35                0             1    1494345599           1494345599   
36                0             1    1494345599           1494345599   
37                0             1    1494345599           1494345599   
38                0             1    1494345599           1494345599   
39                0             1    1494345599           1494345599   

    FstrFinRepayPlan        FuiInvestId  FuiNextRepayTime        ...          \
35        3090246575  94421752916525065        1496592000        ...           
36        3090246575  94421753990529029        1496592000        ...           
37        3090246575  94421755063746564        1496592000        ...           
38        3090246575  94422607614754820        1496592000        ...           
39        3090246575  94579824892100608        1496592000        ...           

    FuiType  FuiRepayOverdueType  continue_invest_20170506  buy_back_20170506  \
35       26                    0                         0                  0   
36       26                    0                         0                  0   
37       26                    0                         0                  0   
38       26                    0                         0                  0   
39       26                    0                         0                  0   

    continue_invest_20170507  buy_back_20170507  continue_invest_20170508  \
35                         0                  0                         0   
36                         0                  0                         0   
37                         0                  0                         0   
38                         0                  0                         0   
39                         0                  0                         0   

    buy_back_20170508  continue_invest_20170509  buy_back_20170509  
35                  0                         0          130000000  
36                  0                         0           80000000  
37                  0                         0          250000000  
38                  0                         0           75000000  
39                  0                         0          400000000  

[5 rows x 26 columns]

In [21]:
df2.FuiFinDuTime.unique()

array([1494345599, 1497023999, 1520611199, 1494431999, 1494518399,
       1494604799, 1494691199, 1494777599, 1494863999])

In [22]:
df2.groupby(['FuiFinDuTime'])['buy_back_20170509'].sum()

FuiFinDuTime
1494345599     2492405480
1494431999       27633423
1494518399         262658
1494604799       51141945
1494691199         961635
1494777599        2155280
1494863999        1317911
1497023999            516
1520611199    19644000000
Name: buy_back_20170509, dtype: int64

In [28]:
df2[df2.FuiFinDuTime == 1520611199].ix[396]

FuiFinancialId              94041524834435078
FuiFinancialInvestId        94043728152936453
FuiInvestUid                93371163117895682
FuiFinUserGroup                             1
FuiFinPerids                               12
FuiFinDuTime                       1520611199
FuiFinNextRepayTime                1494259200
FstrFinRepayPlan                     12000000
FuiInvestId                 94043732443447305
FuiNextRepayTime                   1496592000
FuiNextRepayPrincipal                       0
FuiNextRepayInterest                   240500
FuiToRepayPrincipal                  37000000
FuiRepayDate                       1515167999
FuiPeriods                                 10
FuiCurrentPeriod                            3
FuiType                                    26
FuiRepayOverdueType                         0
continue_invest_20170506                    0
buy_back_20170506                           0
continue_invest_20170507                    0
buy_back_20170507                 

In [30]:
df2[df2.FuiFinDuTime == 1520611199]['FuiFinancialId'].unique()

array([94041524834435078, 94043509105131521, 94041623619731458,
       94043792577953792, 94045483721326598])

In [31]:
df2[df2.FstrFinRepayPlan == 12000000]['FuiFinancialId'].unique()

array([94041524834435078, 94043509105131521, 94041623619731458,
       94043792577953792, 94045483721326598])